//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.12 at 01:12:34 PM IST 
//


package com.searshc.mpuwebservice.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StatusData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="ResponseDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ServiceHeaders">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Store" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="LangId" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApiTracking" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statusData",
    "serviceHeaders",
    "apiTracking"
})
@XmlRootElement(name = "PrintReceiptInfo")
public class PrintReceiptInfo {

    @XmlElement(name = "StatusData", required = true)
    protected PrintReceiptInfo.StatusData statusData;
    @XmlElement(name = "ServiceHeaders", required = true)
    protected PrintReceiptInfo.ServiceHeaders serviceHeaders;
    @XmlElement(name = "ApiTracking", required = true)
    protected String apiTracking;

    /**
     * Gets the value of the statusData property.
     * 
     * @return
     *     possible object is
     *     {@link PrintReceiptInfo.StatusData }
     *     
     */
    public PrintReceiptInfo.StatusData getStatusData() {
        return statusData;
    }

    /**
     * Sets the value of the statusData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintReceiptInfo.StatusData }
     *     
     */
    public void setStatusData(PrintReceiptInfo.StatusData value) {
        this.statusData = value;
    }

    /**
     * Gets the value of the serviceHeaders property.
     * 
     * @return
     *     possible object is
     *     {@link PrintReceiptInfo.ServiceHeaders }
     *     
     */
    public PrintReceiptInfo.ServiceHeaders getServiceHeaders() {
        return serviceHeaders;
    }

    /**
     * Sets the value of the serviceHeaders property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintReceiptInfo.ServiceHeaders }
     *     
     */
    public void setServiceHeaders(PrintReceiptInfo.ServiceHeaders value) {
        this.serviceHeaders = value;
    }

    /**
     * Gets the value of the apiTracking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiTracking() {
        return apiTracking;
    }

    /**
     * Sets the value of the apiTracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiTracking(String value) {
        this.apiTracking = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Store" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="LangId" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "store",
        "langId"
    })
    public static class ServiceHeaders {

        @XmlElement(name = "Store")
        protected short store;
        @XmlElement(name = "LangId")
        protected String langId;

        /**
         * Gets the value of the store property.
         * 
         */
        public short getStore() {
            return store;
        }

        /**
         * Sets the value of the store property.
         * 
         */
        public void setStore(short value) {
            this.store = value;
        }

        /**
         * Gets the value of the langId property.
         * 
         */
        public String getLangId() {
            return langId;
        }

        /**
         * Sets the value of the langId property.
         * 
         */
        public void setLangId(String value) {
            this.langId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *         &lt;element name="ResponseDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responseCode",
        "responseDescription"
    })
    public static class StatusData {

        @XmlElement(name = "ResponseCode")
        protected String responseCode;
        @XmlElement(name = "ResponseDescription", required = true)
        protected String responseDescription;

        /**
         * Gets the value of the responseCode property.
         * 
         */
        public String getResponseCode() {
            return responseCode;
        }

        /**
         * Sets the value of the responseCode property.
         * 
         */
        public void setResponseCode(String value) {
            this.responseCode = value;
        }

        /**
         * Gets the value of the responseDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseDescription() {
            return responseDescription;
        }

        /**
         * Sets the value of the responseDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseDescription(String value) {
            this.responseDescription = value;
        }

    }

}
