//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.23 at 12:11:20 PM IST 
//


package com.searshc.mpuwebservice.domain;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TransactionDetail" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MerchandiseSalesCheckNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="OrderItemDetails">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="OrderItemDetail" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="OrderItemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="FulfillmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StatusData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RespMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApiTracking" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionDetails",
    "statusData",
    "apiTracking"
})
@XmlRootElement(name = "TransactionDetailsResponse")
public class TransactionDetailsResponse {

    @XmlElement(name = "TransactionDetails", required = true)
    protected TransactionDetailsResponse.TransactionDetails transactionDetails;
    @XmlElement(name = "StatusData", required = true)
    protected TransactionDetailsResponse.StatusData statusData;
    @XmlElement(name = "ApiTracking", required = true)
    protected String apiTracking;

    /**
     * Gets the value of the transactionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionDetailsResponse.TransactionDetails }
     *     
     */
    public TransactionDetailsResponse.TransactionDetails getTransactionDetails() {
        return transactionDetails;
    }

    /**
     * Sets the value of the transactionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionDetailsResponse.TransactionDetails }
     *     
     */
    public void setTransactionDetails(TransactionDetailsResponse.TransactionDetails value) {
        this.transactionDetails = value;
    }

    /**
     * Gets the value of the statusData property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionDetailsResponse.StatusData }
     *     
     */
    public TransactionDetailsResponse.StatusData getStatusData() {
        return statusData;
    }

    /**
     * Sets the value of the statusData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionDetailsResponse.StatusData }
     *     
     */
    public void setStatusData(TransactionDetailsResponse.StatusData value) {
        this.statusData = value;
    }

    /**
     * Gets the value of the apiTracking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiTracking() {
        return apiTracking;
    }

    /**
     * Sets the value of the apiTracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiTracking(String value) {
        this.apiTracking = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RespMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responseCode",
        "respMessage"
    })
    public static class StatusData {

        @XmlElement(name = "ResponseCode", required = true)
        protected String responseCode;
        @XmlElement(name = "RespMessage", required = true)
        protected String respMessage;

        /**
         * Gets the value of the responseCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseCode() {
            return responseCode;
        }

        /**
         * Sets the value of the responseCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseCode(String value) {
            this.responseCode = value;
        }

        /**
         * Gets the value of the respMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRespMessage() {
            return respMessage;
        }

        /**
         * Sets the value of the respMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRespMessage(String value) {
            this.respMessage = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TransactionDetail" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MerchandiseSalesCheckNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="OrderItemDetails">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="OrderItemDetail" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="OrderItemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="FulfillmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionDetail"
    })
    public static class TransactionDetails {

        @XmlElement(name = "TransactionDetail")
        protected List<TransactionDetailsResponse.TransactionDetails.TransactionDetail> transactionDetail;

        /**
         * Gets the value of the transactionDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transactionDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransactionDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TransactionDetailsResponse.TransactionDetails.TransactionDetail }
         * 
         * 
         */
        public List<TransactionDetailsResponse.TransactionDetails.TransactionDetail> getTransactionDetail() {
            if (transactionDetail == null) {
                transactionDetail = new ArrayList<TransactionDetailsResponse.TransactionDetails.TransactionDetail>();
            }
            return this.transactionDetail;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MerchandiseSalesCheckNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="OrderItemDetails">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="OrderItemDetail" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="OrderItemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="FulfillmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "merchandiseSalesCheckNumber",
            "orderItemDetails"
        })
        public static class TransactionDetail {

            @XmlElement(name = "MerchandiseSalesCheckNumber")
            protected String merchandiseSalesCheckNumber;
            @XmlElement(name = "OrderItemDetails", required = true)
            protected TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails orderItemDetails;

            /**
             * Gets the value of the merchandiseSalesCheckNumber property.
             * 
             */
            public String getMerchandiseSalesCheckNumber() {
                return merchandiseSalesCheckNumber;
            }

            /**
             * Sets the value of the merchandiseSalesCheckNumber property.
             * 
             */
            public void setMerchandiseSalesCheckNumber(String value) {
                this.merchandiseSalesCheckNumber = value;
            }

            /**
             * Gets the value of the orderItemDetails property.
             * 
             * @return
             *     possible object is
             *     {@link TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails }
             *     
             */
            public TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails getOrderItemDetails() {
                return orderItemDetails;
            }

            /**
             * Sets the value of the orderItemDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails }
             *     
             */
            public void setOrderItemDetails(TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails value) {
                this.orderItemDetails = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="OrderItemDetail" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="OrderItemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="FulfillmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "orderItemDetail"
            })
            public static class OrderItemDetails {

                @XmlElement(name = "OrderItemDetail")
                protected List<TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails.OrderItemDetail> orderItemDetail;

                /**
                 * Gets the value of the orderItemDetail property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the orderItemDetail property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getOrderItemDetail().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails.OrderItemDetail }
                 * 
                 * 
                 */
                public List<TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails.OrderItemDetail> getOrderItemDetail() {
                    if (orderItemDetail == null) {
                        orderItemDetail = new ArrayList<TransactionDetailsResponse.TransactionDetails.TransactionDetail.OrderItemDetails.OrderItemDetail>();
                    }
                    return this.orderItemDetail;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="OrderItemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="FulfillmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "orderItemID",
                    "fulfillmentName"
                })
                public static class OrderItemDetail {

                    @XmlElement(name = "OrderItemID")
                    protected int orderItemID;
                    @XmlElement(name = "FulfillmentName", required = true)
                    protected String fulfillmentName;

                    /**
                     * Gets the value of the orderItemID property.
                     * 
                     */
                    public int getOrderItemID() {
                        return orderItemID;
                    }

                    /**
                     * Sets the value of the orderItemID property.
                     * 
                     */
                    public void setOrderItemID(int value) {
                        this.orderItemID = value;
                    }

                    /**
                     * Gets the value of the fulfillmentName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFulfillmentName() {
                        return fulfillmentName;
                    }

                    /**
                     * Sets the value of the fulfillmentName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFulfillmentName(String value) {
                        this.fulfillmentName = value;
                    }

                }

            }

        }

    }

}
