//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 02:31:05 PM CDT 
//


package com.searshc.mpuwebservice.vo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fetchTime" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="productInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="partNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mfgPartNumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="shortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shcDivision" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="season" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="numReview" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="imageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="onlineImageUrls">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="onlineImageUrl" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="location">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="price" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="priceMultiple" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="priceMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="qtyAvailable" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                           &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="st" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="phone" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="dist" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="upc" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="ksn" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="div" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="item" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="sku" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="itemId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fetchTime",
    "productInfo"
})
@XmlRootElement(name = "productInfoResponse")
public class ProductInfoResponse {

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="partNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mfgPartNumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="shortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shcDivision" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="season" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="numReview" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="imageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="onlineImageUrls">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="onlineImageUrl" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="location">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="price" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="priceMultiple" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="priceMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="qtyAvailable" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                 &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="st" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="phone" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="dist" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="upc" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="ksn" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="div" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="item" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="sku" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="itemId" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "partNumber",
        "mfgPartNumber",
        "shortDescription",
        "shcDivision",
        "color",
        "height",
        "width",
        "length",
        "country",
        "season",
        "rating",
        "numReview",
        "imageUrl",
        "onlineImageUrls",
        "location"
    })
    public static class ProductInfo {

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="price" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="priceMultiple" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="priceMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="qtyAvailable" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}short" />
         *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="st" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="zip" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="phone" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="dist" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "price",
            "qtyAvailable"
        })
        public static class Location {

            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="priceMultiple" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="priceMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "amount",
                "type",
                "priceMultiple",
                "priceMessage"
            })
            public static class Price {

                protected float amount;
                @XmlElement(required = true)
                protected String priceMessage;
                protected byte priceMultiple;
                
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the amount property.
                 * 
                 */
                public float getAmount() {
                    return amount;
                }

                /**
                 * Gets the value of the priceMessage property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPriceMessage() {
                    return priceMessage;
                }

                /**
                 * Gets the value of the priceMultiple property.
                 * 
                 */
                public byte getPriceMultiple() {
                    return priceMultiple;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the amount property.
                 * 
                 */
                public void setAmount(float value) {
                    this.amount = value;
                }

                /**
                 * Sets the value of the priceMessage property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPriceMessage(String value) {
                    this.priceMessage = value;
                }

                /**
                 * Sets the value of the priceMultiple property.
                 * 
                 */
                public void setPriceMultiple(byte value) {
                    this.priceMultiple = value;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }
            @XmlAttribute
            protected String addr;
            @XmlAttribute
            protected String city;
            @XmlAttribute
            protected String dist;
            @XmlAttribute
            protected String phone;
            protected List<ProductInfoResponse.ProductInfo.Location.Price> price;
            protected int qtyAvailable;
            @XmlAttribute
            protected String st;
            @XmlAttribute
            protected String storeNumber;

            @XmlAttribute
            protected String zip;

            /**
             * Gets the value of the addr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddr() {
                return addr;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Gets the value of the dist property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDist() {
                return dist;
            }

            /**
             * Gets the value of the phone property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public String getPhone() {
                return phone;
            }

            /**
             * Gets the value of the price property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the price property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPrice().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ProductInfoResponse.ProductInfo.Location.Price }
             * 
             * 
             */
            public List<ProductInfoResponse.ProductInfo.Location.Price> getPrice() {
                if (price == null) {
                    price = new ArrayList<ProductInfoResponse.ProductInfo.Location.Price>();
                }
                return this.price;
            }

            /**
             * Gets the value of the qtyAvailable property.
             * 
             */
            public int getQtyAvailable() {
                return qtyAvailable;
            }

            /**
             * Gets the value of the st property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSt() {
                return st;
            }

            /**
             * Gets the value of the number property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public String getStoreNumber() {
                return storeNumber;
            }

            /**
             * Gets the value of the zip property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public String getZip() {
                return zip;
            }

            /**
             * Sets the value of the addr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddr(String value) {
                this.addr = value;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Sets the value of the dist property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDist(String value) {
                this.dist = value;
            }

            /**
             * Sets the value of the phone property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setPhone(String value) {
                this.phone = value;
            }

            /**
             * Sets the value of the qtyAvailable property.
             * 
             */
            public void setQtyAvailable(int value) {
                this.qtyAvailable = value;
            }

            /**
             * Sets the value of the st property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSt(String value) {
                this.st = value;
            }

            /**
             * Sets the value of the number property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setStoreNumber(String value) {
                this.storeNumber = value;
            }


            /**
             * Sets the value of the zip property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setZip(String value) {
                this.zip = value;
            }

        }
        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="onlineImageUrl" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "onlineImageUrl"
        })
        public static class OnlineImageUrls {

            protected List<String> onlineImageUrl;

            /**
             * Gets the value of the onlineImageUrl property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the onlineImageUrl property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOnlineImageUrl().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getOnlineImageUrl() {
                if (onlineImageUrl == null) {
                    onlineImageUrl = new ArrayList<String>();
                }
                return this.onlineImageUrl;
            }

        }
        @XmlElement(required = true)
        protected String color;
        @XmlElement(required = true)
        protected String country;
        @XmlElement(required = true)
        protected String description;
        @XmlAttribute
        protected String div;
        protected float height;
        @XmlElement(required = true)
        protected String imageUrl;
        @XmlAttribute
        protected String item;
        @XmlAttribute
        protected String itemId;
        @XmlAttribute
        protected String ksn;
        protected float length;
        @XmlElement(required = true)
        protected ProductInfoResponse.ProductInfo.Location location;
        protected short mfgPartNumber;
        protected byte numReview;
        @XmlElement(required = true)
        protected ProductInfoResponse.ProductInfo.OnlineImageUrls onlineImageUrls;
        @XmlElement(required = true)
        protected String partNumber;
        protected float rating;
        @XmlElement(required = true)
        protected String season;
        protected byte shcDivision;
        @XmlElement(required = true)
        protected String shortDescription;
        @XmlAttribute
        protected String sku;

        @XmlAttribute
        protected String upc;

        protected float width;

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Gets the value of the div property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public String getDiv() {
            return div;
        }

        /**
         * Gets the value of the height property.
         * 
         */
        public float getHeight() {
            return height;
        }

        /**
         * Gets the value of the imageUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImageUrl() {
            return imageUrl;
        }

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public String getItem() {
            return item;
        }

        /**
         * Gets the value of the itemId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public String getItemId() {
            return itemId;
        }

        /**
         * Gets the value of the ksn property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public String getKsn() {
            return ksn;
        }

        /**
         * Gets the value of the length property.
         * 
         */
        public float getLength() {
            return length;
        }

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link ProductInfoResponse.ProductInfo.Location }
         *     
         */
        public ProductInfoResponse.ProductInfo.Location getLocation() {
            return location;
        }

        /**
         * Gets the value of the mfgPartNumber property.
         * 
         */
        public short getMfgPartNumber() {
            return mfgPartNumber;
        }

        /**
         * Gets the value of the numReview property.
         * 
         */
        public byte getNumReview() {
            return numReview;
        }

        /**
         * Gets the value of the onlineImageUrls property.
         * 
         * @return
         *     possible object is
         *     {@link ProductInfoResponse.ProductInfo.OnlineImageUrls }
         *     
         */
        public ProductInfoResponse.ProductInfo.OnlineImageUrls getOnlineImageUrls() {
            return onlineImageUrls;
        }

        /**
         * Gets the value of the partNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartNumber() {
            return partNumber;
        }

        /**
         * Gets the value of the rating property.
         * 
         */
        public float getRating() {
            return rating;
        }

        /**
         * Gets the value of the season property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeason() {
            return season;
        }

        /**
         * Gets the value of the shcDivision property.
         * 
         */
        public byte getShcDivision() {
            return shcDivision;
        }

        /**
         * Gets the value of the shortDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortDescription() {
            return shortDescription;
        }

        /**
         * Gets the value of the sku property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public String getSku() {
            return sku;
        }

        /**
         * Gets the value of the upc property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public String getUpc() {
            return upc;
        }

        /**
         * Gets the value of the width property.
         * 
         */
        public float getWidth() {
            return width;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Sets the value of the div property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setDiv(String value) {
            this.div = value;
        }

        /**
         * Sets the value of the height property.
         * 
         */
        public void setHeight(float value) {
            this.height = value;
        }

        /**
         * Sets the value of the imageUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImageUrl(String value) {
            this.imageUrl = value;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Sets the value of the itemId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setItemId(String value) {
            this.itemId = value;
        }

        /**
         * Sets the value of the ksn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setKsn(String value) {
            this.ksn = value;
        }

        /**
         * Sets the value of the length property.
         * 
         */
        public void setLength(float value) {
            this.length = value;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductInfoResponse.ProductInfo.Location }
         *     
         */
        public void setLocation(ProductInfoResponse.ProductInfo.Location value) {
            this.location = value;
        }

        /**
         * Sets the value of the mfgPartNumber property.
         * 
         */
        public void setMfgPartNumber(short value) {
            this.mfgPartNumber = value;
        }

        /**
         * Sets the value of the numReview property.
         * 
         */
        public void setNumReview(byte value) {
            this.numReview = value;
        }

        /**
         * Sets the value of the onlineImageUrls property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductInfoResponse.ProductInfo.OnlineImageUrls }
         *     
         */
        public void setOnlineImageUrls(ProductInfoResponse.ProductInfo.OnlineImageUrls value) {
            this.onlineImageUrls = value;
        }

        /**
         * Sets the value of the partNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartNumber(String value) {
            this.partNumber = value;
        }

        /**
         * Sets the value of the rating property.
         * 
         */
        public void setRating(float value) {
            this.rating = value;
        }

        /**
         * Sets the value of the season property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeason(String value) {
            this.season = value;
        }

        /**
         * Sets the value of the shcDivision property.
         * 
         */
        public void setShcDivision(byte value) {
            this.shcDivision = value;
        }

        /**
         * Sets the value of the shortDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortDescription(String value) {
            this.shortDescription = value;
        }

        /**
         * Sets the value of the sku property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSku(String value) {
            this.sku = value;
        }


        /**
         * Sets the value of the upc property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setUpc(String value) {
            this.upc = value;
        }


        /**
         * Sets the value of the width property.
         * 
         */
        public void setWidth(float value) {
            this.width = value;
        }

    }
    protected short fetchTime;

    @XmlElement(required = true)
    protected ProductInfoResponse.ProductInfo productInfo;

    /**
     * Gets the value of the fetchTime property.
     * 
     */
    public short getFetchTime() {
        return fetchTime;
    }

    /**
     * Gets the value of the productInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProductInfoResponse.ProductInfo }
     *     
     */
    public ProductInfoResponse.ProductInfo getProductInfo() {
        return productInfo;
    }

    /**
     * Sets the value of the fetchTime property.
     * 
     */
    public void setFetchTime(short value) {
        this.fetchTime = value;
    }


    /**
     * Sets the value of the productInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductInfoResponse.ProductInfo }
     *     
     */
    public void setProductInfo(ProductInfoResponse.ProductInfo value) {
        this.productInfo = value;
    }

}
